---
title: "Cluster Selection Supplement"
author: "Terry Slenn"
date: "November 9, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r set seed}
#sample(1:10000, size = 1) ## Randomly choose seed: 8367
set.seed(8367) ## Manually set seed for reproducible results
```

## Northwest DC Sample

Previous zip codes have been removed.

```{r NWDC}
zips <- tibble(zipcode = c(20004,20005,20008,20009),
               pops = c(1717,13234,29527,51542))

sample_n(zips, 4, weight = pops)
```

## Arlington

```{r Arl}
zips <- tibble(zipcode = c(22201,22202,22203,22205,22207,22209,22213),
               pops = c(37524,23509,24188,18823,33431,12335,3317))

sample_n(zips, 2, weight = pops)
```


## Bethesda/Rockville

```{r Beth}
zips <- tibble(zipcode = c(20814,20815,20816,20850,20852,20855,20895), #20851 and 20817 had no regular grocery stores
               pops = c(29005,30476,16248,33557,34956,17251,18713))

sample_n(zips, 2, weight = pops)
```

